### ISSUE TITLE
undefined is not an Object PushwooshModule.init on ios 

### ISSUE THREAD

**Issue by RORrvtech** [Pushwoosh/pushwoosh-react-native-sample#3] opened 2018-04-13 08:46 UTC
[
![simulator screen shot - iphone 6 - 2018-04-13 at 14 14 33](https://user-images.githubusercontent.com/28922621/38725464-09f57312-3f25-11e8-9c44-255bb99640a1.png)
](url)
info 

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.1.4
  Yarn: 0.27.5
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

While register the component 

related to  [https://github.com/Pushwoosh/pushwoosh-react-native-plugin/issues/23](url)

**Comment by wfhm** [comment] 2018-04-23 17:37
Closed as duplicate of [#23](https://github.com/Pushwoosh/pushwoosh-react-native-plugin/issues/23).

**Closed by wfhm** 2018-04-23 17:37 UTC
